### ISSUE TITLE
QGIS OpenGeo Explorer: Drag 'n Drop functionality broken on OS X

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#839]
QGIS 2.6.1, OS X 10.10

Python error when trying to drag a GeoServer layer into QGIS (Layers can be added from the context menu without error): https://gist.github.com/tbarsballe/b2f9eac7cc2a242edbce. Also occurs if you try to drag the layer to a group, to GeoWebcache or anywhere else.

Dragging styles to/from QGIS from/to the OpenGeo plugin fails with a python error, as with layers above.

Cannot drag files/layers from the QGIS browser into the PostGIS section (Mouse pointer shows an X)

When draggin a layer from the QGIS section of the opengeo plugin into PostGIS, get Error: No module named ogr2ogrtopostgis

When dragging a table from PostGIS to anywhere, get python error: https://gist.github.com/tbarsballe/3323561726ba86905f47

**Comment by volaya** [comment]
The last error seems to be caused by the database object having a null password... Can you confirm that there is no password in that PostGIS db? In that case, that might affect other parts of the plugin that use similar code to establish the connection

I added this fix to prevent that case

https://github.com/boundlessgeo/suite-qgis-plugin/commit/4754361c66f70e81bed46216a91b43f201c7bafa

The No module named ogr2ogrtopostgis error is a known issue and will be fixed once the latest version of Processing is installed

I haven't been able to reproduce the other ones in a Windows machine, so they are probably OSX specific. Will have a look at them later

**Comment by tbarsballe** [comment]
You are right, the DB does not have a password. As noted on the title, pretty sure these are all OS X specific.

**Comment by tbarsballe** [comment]
This issue was moved to boundlessgeo/suite-qgis-plugin#158
