### ISSUE TITLE
QGIS OpenGeo Explorer: Must restart QGIS for OpenGeo Explorer to show up (OS X)

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#845]
After installing OpenGeo Explorer, must restart QGIS for the plugin to show up. OS X only (I suspect this is an issue with updating the menu bar)

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by dakcarto** [comment]
Can not replicate here on OS X 10.9.5, QGIS 2.6.1. After installing the plugin, you will still need to check (enable) the plugin in the Manager, if it was not already.

There is a known issue when up/downgrading an active plugin instance; causes crash on Mac and Win due to invalid access to abandoned C++ objects, or possibly cross-thread issue.

**Comment by tbarsballe** [comment]
This issue was moved to boundlessgeo/suite-qgis-plugin#162
